# Generated by Django 3.1.6 on 2021-02-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='mascot',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
