# Generated by Django 3.1.6 on 2021-02-25 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20210223_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='score_1',
            field=models.IntegerField(blank=True, help_text='Team 1 final score', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_2',
            field=models.IntegerField(blank=True, help_text='Team 2 final score', null=True),
        ),
        migrations.CreateModel(
            name='ParticipatesIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(through='tournament.ParticipatesIn', to='tournament.Team'),
        ),
    ]
