# Generated by Django 3.1.6 on 2021-02-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20210224_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['date_of']},
        ),
    ]
