# Generated by Django 3.1.6 on 2021-02-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20210225_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_1',
            field=models.IntegerField(blank=True, help_text='Team 1 eliminations', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_2',
            field=models.IntegerField(blank=True, help_text='Team 2 eliminations', null=True),
        ),
    ]
